# Generated by Django 4.0.6 on 2022-07-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0002_alter_entrada_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='contenido',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
