# Generated by Django 4.0.6 on 2022-07-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0003_alter_entrada_contenido_alter_entrada_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='viewmore',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
